color: null
fieldLayouts:
  12c16c0f-5fea-4521-87e7-0426f5dd7f7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a442587-9a1d-41f9-92a7-1a42eb209d65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73454780-1162-42ed-a04d-82640c6f6061
            handle: null
            includeInCards: true
            instructions: null
            label: Seite
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 602c9a0e-74be-4b68-84a7-c4ba8ca9fe95
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c8f1bdc6-8e91-4fd3-83e5-f96a507bb27c # Link Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1b39bf5-8d06-4ffe-8548-3c3824e4eb65
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 42b295ab-e778-4c44-87d7-ad7aa073f4d3 # Linktext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daf5a796-cbd5-4904-90b0-d5a0a31b4787
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 306163ac-0987-4397-be37-3465f005e2a0
        userCondition: null
handle: internalLink
hasTitleField: false
icon: ''
name: Intern
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
