color: null
fieldLayouts:
  4ef755f2-d533-49d0-b846-328aa28943f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6fc95d6d-5f0d-47db-9505-2dcfa358def6 # Textabschnitt - Absatz - Text
            handle: null
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1489fd02-e8e7-4a74-9988-556612be5ca4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31708854-6ffb-4072-8871-a81ffeb4903e
        userCondition: null
handle: paragraph
hasTitleField: false
icon: null
name: Absatz
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
