childBlocks:
  - text
  - link
  - contactForm
color: teal
conditions: null
description: ''
enabled: true
field: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
group: null
groupChildBlockTypes: true
handle: group
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Gruppe
topLevel: true
