childBlocks: null
color: blue
conditions: null
description: ''
enabled: true
field: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
fieldLayouts:
  b021f96b-d828-4889-89c0-c6ee5e7c3119:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6ba183da-ef91-4615-850d-4b82daf96849 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22aa9e87-01af-440d-ae20-75739ee4c986
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: 46b0dd4d-46c6-4b79-9b85-9fb9890ca980
        userCondition: null
group: null
groupChildBlockTypes: true
handle: link
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Link
topLevel: false
