childBlocks: null
color: amber
conditions: null
description: ''
enabled: true
field: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
fieldLayouts:
  93bd48e6-6deb-43d9-aa71-f6b6f8ba6c67:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b40ec017-c91e-4689-b32c-0ba8fda3a466 # Text Editor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bbd4130-051f-4be9-9e1c-f2ad5c46d963
            userCondition: null
            warning: null
            width: 100
        name: Allgemein
        uid: a2ab6c54-a0cf-4992-adb4-b850da593c6e
        userCondition: null
group: null
groupChildBlockTypes: true
handle: text
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
topLevel: true
