columnSuffix: dsydofgq
contentColumnType: text
handle: altText
instructions: ''
name: 'Alt Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: Alternativ-Text
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
