columnSuffix: null
handle: headlineType
instructions: null
name: 'Textabschnitt - Überschrift - Typ'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - H1
        -
          - value
          - h1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H2
        -
          - value
          - h2
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - H3
        -
          - value
          - h3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H4
        -
          - value
          - h4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H5
        -
          - value
          - h5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H6
        -
          - value
          - h6
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
