columnSuffix: null
handle: href
instructions: null
name: 'Link - Extern - Linkziel'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
