columnSuffix: null
handle: inactive
instructions: null
name: Inaktiv
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
