columnSuffix: null
handle: linkLayout
instructions: null
name: 'Link Layout'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Standard
        -
          - value
          - default
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Button
        -
          - value
          - button
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
