columnSuffix: null
handle: newWindow
instructions: null
name: 'Link - Extern - Neues Fenster'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
