columnSuffix: kihhpxsu
handle: textHTML
instructions: null
name: 'Text Editor'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 12853f5e-57c7-40e4-908a-b7be4ce30bc7 # Default
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
