columnSuffix: null
handle: width
instructions: null
name: Breite
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Standard
        -
          - value
          - default
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Volle Breite'
        -
          - value
          - full
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
